server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_userdb
    username: postgres
    password: loukik123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true

